# This is a basic workflow to help you get started with Actions
name: Build and Push Flask App to Docker Hub

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Automatic Tagging of Releases
        id: incremenent-git-tag
        run: |
          bash ./build/git_update.sh -v patch

      - name: Build docker image
        env:
          IMAGE_TAG: ${{ steps.incremenent-git-tag.outputs.git-tag }}
          DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/flaskapp-aws:$IMAGE_TAG
        run: |
          echo $IMAGE_TAG
          docker build -t $DOCKER_IMAGE .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
          docker push $DOCKER_IMAGE
